-- ====================================================================
-- GANGACHECK.ES - Esquema de Base de Datos en Supabase (PostgreSQL)
-- Copia y pega este script en el "SQL Editor" de tu proyecto de Supabase
-- ====================================================================

-- 1. Tabla de Análisis y Escaneos de la Web
CREATE TABLE IF NOT EXISTS scans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform TEXT NOT NULL DEFAULT 'wallapop',
    item_id TEXT,
    url TEXT NOT NULL,
    title TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    normalized_product TEXT,
    score NUMERIC(3, 1) NOT NULL,
    verdict TEXT NOT NULL,
    market_price NUMERIC(10, 2),
    savings NUMERIC(10, 2),
    savings_pct NUMERIC(5, 2),
    risk_level TEXT DEFAULT 'NORMAL',
    seller_rating NUMERIC(3, 1),
    seller_reviews INTEGER DEFAULT 0,
    has_shipping BOOLEAN DEFAULT TRUE,
    details_json JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabla de Precios de Referencia (Benchmarks del Mercado)
CREATE TABLE IF NOT EXISTS market_benchmarks (
    product_key TEXT PRIMARY KEY,
    display_name TEXT NOT NULL,
    median_price NUMERIC(10, 2) NOT NULL,
    min_normal_price NUMERIC(10, 2) NOT NULL,
    max_normal_price NUMERIC(10, 2) NOT NULL,
    category TEXT,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabla de Recolección de Anuncios en Crudo (Histórico Continuo)
CREATE TABLE IF NOT EXISTS raw_listings (
    id TEXT PRIMARY KEY,
    platform TEXT NOT NULL DEFAULT 'wallapop',
    title TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    keyword TEXT,
    seller_name TEXT,
    seller_reviews INTEGER DEFAULT 0,
    has_shipping BOOLEAN DEFAULT TRUE,
    url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Datos Iniciales de Benchmarks de Mercado
INSERT INTO market_benchmarks (product_key, display_name, median_price, min_normal_price, max_normal_price, category)
VALUES
    ('ps5_disc', 'PlayStation 5 (Con Lector)', 380.0, 320.0, 430.0, 'Consolas'),
    ('ps5_digital', 'PlayStation 5 Digital', 330.0, 280.0, 370.0, 'Consolas'),
    ('ps5_slim', 'PlayStation 5 Slim', 410.0, 360.0, 460.0, 'Consolas'),
    ('switch_oled', 'Nintendo Switch OLED', 230.0, 190.0, 270.0, 'Consolas'),
    ('switch_v2', 'Nintendo Switch V2', 160.0, 130.0, 190.0, 'Consolas'),
    ('xbox_series_x', 'Xbox Series X 1TB', 360.0, 300.0, 410.0, 'Consolas'),
    ('steam_deck_512', 'Steam Deck 512GB', 320.0, 270.0, 380.0, 'Consolas'),
    ('iphone_13_128', 'Apple iPhone 13 128GB', 360.0, 300.0, 420.0, 'Móviles'),
    ('iphone_14_128', 'Apple iPhone 14 128GB', 460.0, 400.0, 520.0, 'Móviles'),
    ('iphone_15_128', 'Apple iPhone 15 128GB', 580.0, 510.0, 650.0, 'Móviles'),
    ('airpods_pro_2', 'Apple AirPods Pro 2', 150.0, 120.0, 180.0, 'Audio'),
    ('rtx_4070', 'Tarjeta Gráfica RTX 4070 12GB', 480.0, 420.0, 550.0, 'Informática')
ON CONFLICT (product_key) DO NOTHING;

-- 5. Habilitar lectura pública (Row Level Security permisiva para lectura de la web)
ALTER TABLE scans ENABLE ROW LEVEL SECURITY;
ALTER TABLE market_benchmarks ENABLE ROW LEVEL SECURITY;
ALTER TABLE raw_listings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Lectura pública de scans" ON scans FOR SELECT USING (true);
CREATE POLICY "Inserción pública de scans" ON scans FOR INSERT WITH CHECK (true);
CREATE POLICY "Lectura pública de benchmarks" ON market_benchmarks FOR SELECT USING (true);
CREATE POLICY "Lectura pública de raw_listings" ON raw_listings FOR SELECT USING (true);
CREATE POLICY "Inserción de raw_listings" ON raw_listings FOR ALL USING (true);
